#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS test;
GRANT ALL PRIVILEGES ON test.* TO '${MYSQL_USER}'@'%';
GRANT CREATE, DROP ON *.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
